= Arquillian Non-Deploying Container 

This container does not deploy anything, instead it returns URI based on provided +baseURI+ and to-be-deployed-by-somebody-else archive name.

Its purpose is to allow Arquillian to inject URI/URL into @Deployment for tests that connect to already existing deployment, installed by different means.

=== Usage

1. Put container as +test+ scoped dependency to the project

2. Define properties in _arquillian.xml_ that would make possible to construct URL.
    
    * +baseURI+ base URI of the deployment, this is *required* 
    * +contextRootRemap+ a JSON map to remap context root given by deployment to different path
    * +check+ fully qualified class name of a status check to perform, when not set, by default it equals to +org.jboss.aerogear.test.arquillian.container.check.impl.HTTPCodeStatusCheck+
    * +checkTimeout+ integer value bigger then 0, maximum time for which check will be performed. When check is not satisfied until that time, test fails. By default 300 seconds.

TIP: Remapping can be used to modify deployment URI for archives that have different context path on local container and on remote container

== TODO

1. Implement a ping for constructed URL - to check that application was indeed deployment at given location first
