= AeroGear Unified Push Server REST API 

This project contains REST API wrappers for the [aerogear-unified-push-server](https://github.com/aerogear/aerogear-unified-push-server) project.

It is handy in order to define tests that exercise or need to access REST endpoints provided by UnifiedPush Server.

== Usage

Include this into your project

    <dependency>
        <groupId>org.jboss.aerogear.test</groupId>
        <artifactId>aerogear-ups-rest-api</artifactId>
        <version>${version}</version>
    </dependency>

== Release new version

Release new version every time underlying UnifiedPush API model is changed. Use following version scheme:

    ups.version

In case there is need to release another version based on same API version, use +-${ups.version}-${increment}+, for instance +1.0.0.Beta1-1+

Maven Release plugin does not work for projects that are not represented by Git repository.
Follow this process to release new version

1. Update version to release version in pom.xml
2. Execute +mvn deploy -Pjboss-release+
3. Tag current commit via +git tag+
4. Bump version to next development version
