== JBossStarter and JBossStopper

By this Spacelift task you start JBoss instance like this:

[source,java]
----
JBossManager manager = Tasks.prepare(JBossStarter.class)
    .configuration(new JBossManagerConfiguration().setJbossHome(JBOSS_HOME))
    .execute()
    .await();
----

The previous command returns JBossManager via which you are stopping it like this:

[source,java]
----
Tasks.chain(manager, JBossStopper.class).execute().await();
----

In order to start and immediately stop container by one-liner, do it like this:

[source,java]
----
Tasks.prepare(JBossStarter.class)
    .configuration(new JBossManagerConfiguration().setJbossHome(JBOSS_HOME))
    .then(JBossStopper.class)
    .execute()
    .await();
----

You can start servers in domain as well:

[source,java]
----
Tasks.prepare(JBossStarter.class)
    .configuration(new JBossManagerConfiguration().setJbossHome(JBOSS_HOME).domain())
    .then(JBossStopper.class)
    .execute()
    .await();
----

By default, configuration of the container is suited for Wildfly. When you want to use options for Java process for 
different container, please use +setContainerType(CONTAINER_TYPE)+ method on manager configuration object.

If you want to use JBoss instance located by your +JBOSS_HOME+ property, you can omit +configuration+ method.

== JBossCLI

JBossCLI provides a way how to send commands via jboss-cli tool bundled in JBoss distribution via Java. After you 
have started JBoss instance by +JBossStarter+, use it e.g. like this:

[source,java]
----
Tasks.prepare(JBossCLI.class)
    .environment("JBOSS_HOME", JBOSS_HOME)
    .connect()
    .cliCommand("quit")
    .execute()
    .await();
----

You can omit +environment+ if you are satisfied with defaults. Just shown command does this:

----
[shell]$ $JBOSS_HOME/bin/jboss-cli.sh --connect --command=quit
----

+JBossCLI+ is a wrapper around jboss-cli scripts. It is multiplatform. You can automatically use it at Linux, Macs and Windows.
Please investigate its API to get to know how to use it. Setters for that tool just copy parameters you can add to command line version of it.

=== Testing of this project

In order to try other container from default located in +target/jboss+ in tests, you need to set system property +jboss.home+ like

----
$ mvn clean test -Djboss.home=[path_to_jboss_home_of_my_interest]
----

If you want to try to test another container different from JBoss AS 7, you have to specify its container type by system property +containerType+

----
$ mvn clean test -DcontainerType={AS7,EAP,WILDFLY} -Djboss.home={container directory}
----

This project uses https://github.com/arquillian/arquillian-spacelift-gradle-plugin[Spacelift Gradle plugin] as well. You can test JBoss AS 7 and Wildfly 8 just by executing:

----
$ ./gradlew test
----

JBoss AS 7 and Wildfly zips are downloaded automatically and tests for both containers are executed. If you want to test EAP containers, 
it is up to you to provide Spacelift Gradle plugin installation for it since this container is not publicly available.

== Release new version

Maven Release plugin does not work for projects that are not represented by Git repository.
Follow this process to release new version

1. Update version to release version in pom.xml
2. Execute +mvn deploy -Pjboss-release+
3. Tag current commit via +git tag+
4. Bump version to next development version
