= Aerogear Test Environment Plugin

This Gradle plugin is able to prepare test environment and execute tests.
Plugin is using Arquillian Spacelift project to execute external commands.

In order to enable the plugin, define:

[source,groovy]
----
apply plugin: 'aerogear-test-env'
----

== Gradle Tasks

This plugin provides following tasks:

prepare-env::
    Installs all installations defined by profile
test::
    Executes tests defined in profile. Depends on +prepare-env+
show-configuration::
    Shows global configuration and available profiles

== DSL

Plugin uses following DSL structure:

[code,groovy]
----
aerogearTestEnv {

    workspace
    installationsDir
    localRepository
    killServers
    keystoreFile
    truststoreFile
    enableStaging
    enableSnapshots

    tools {
        tool1 {
        }
    }

    profiles {
        profile1 {
        }
    }

    installations {
        installation1 {
        }
    }

    tests {
        test1 {
        }
    }

    
}
----

globalSetupProperties::
    There are a few properties with sane default. You can modify them to alter execution flow.
+
* workspace - a directory where you work, by default this directory 
* installationsDir - a directory where installation files are cached
* localRepository - Maven local repository path
* killServers - {true|false} whether to kill Java processes first
* keystoreFile - path to JKS keystore file
* truststoreFile - path to JKS truststore file
* enableStaging - enable JBoss Staging repository
* enableSnapshots - enable JBoss Snapshots repository

tools::
    Tools allow you to define external commands that should be available on local system. Syntax is following:
+
[source,groovy]
----
toolName {
    command = string OR list of strings OR block OR map of strings, list of strings or block
}
----
+
command::
    Command defines what will be executed. In case you provide _string_ or _list of strings_, it will be transformed to 
    Spacelift +CommandTool+. In case you are using _block_, you are supposed to return +CommandTool+. In case of
    map, you can use *windows*, *linux*, *mac* and *solaris* keys that will match the platform. The block will register a +CommandTool+ 
    you can retrieve by +GradleSpacelift.tools('toolName')+ later on.
    Following tools are always expected to be present: _ant_ and _mvn_

profiles::
    Profiles consist of installations to be installed and tests to be executed. You can use -Pprofile=_profileName_ to trigger
    specific profile, otherwise default profile is triggered. _default_ profile is expected to be present. Note, you need
    define profileName quoted in case of _default_.
+
[source,groovy]
----
profileName {
    enabledInstallations = ['installation1', 'installation2']
    tests = ['test1', 'test3', 'test27']
}
----

installations::
    Installations provides a way how to bring additional tools to you test environment. Installation is automatically downloaded
    or fetched from local cache and extracted, based on current OS.
+
[source,groovy]
----
installationName {
    product = string
    version = string
    fileName = string OR map of strings
    remoteUrl = string OR map of strings
    home = string OR map of strings
    autoExtract = true | false
    tool {
        name = 'toolName'
        command = same as command for tool in tools block
    }
    postActions {
    }
}
----
+
    Following properties are used:
+
* product - name of product, used for storing installation in _installationsDir_
* version - version of product, used for storing installation in _installationsDir_
* fileName - name of file as downloaded in _workspace_. Can be map, same keys as for _tool_
* remoteUrl - URL where to download from. Can be map, same keys as for _tool_
* home - name of dir in _workspace_ where installation is extracted. Can be map, same keys as for _tool_
* autoExtract - by default +true+, consider installation an archive and extract it to WORKSPACE directory
* tool - allows to define +tool+ that will be available after installation is done
+ postActions - defines action to be performed after installation is extracted
+
    Note: Installation can bring multiple tools. You can provide more then one +tool+ block.

tests::
    Tests define a block of commands to be executed in *test* Gradle task. If you provide +dataProvider+ block, test
    execution (including before and after test phases) will iterate over data provided.
+
[source,groovy]
----
testName {
    dataProvider {
        // return an array here, allows to parametrize tests
    }
    beforeSuite { 
        // executed once prior all tests
    }
    beforeTest { value ->
        // executed prior test
    }
    execute { value ->
        // your commands here
    }
    afterTest { value ->
        // executed after test
    }
    afterSuite() {
        // executed once prior all tests
    }
}
----
+

== Execution parameters

It is possible to modify what tests will be run and what installations will be installed. Apart from profile option, you can use:

[source,bash]
----
-Pinstallations=comma,separated,values
-Ptests=comma,separated,values
----

This will ignore installations and tests defined by profile and instead will install +comma+, +separated+ and +value+. If _test_ task is executed,
it will perform test execution for tests +comma+, +separated+ and +value+.

If you need to reference profile, installations or tests from Gradle script, these are exposed as:

* +project.selectedProfile+
* +project.selectedInstallations+
* +project.selectedTests+

All represented by appropriate object.


== Default values

Groovy allows user to specify additional project properties using +ext+ block:

[source,groovy]
----
ext {
    property = value
}
----

This plugin additionally allows following goodies for property definitions:

Default values::
    If a property starts with +default+, it is used if user won't override it from command line. Example: +defaultAndroidVersion=[19]+ will 
    become available as +androidVersion+ property in the project.
Overriding default values::
    User can override any default value by using +-PpropertyName=value+ from command line. Example: +-PandroidVersion=17,18+ will override
    +defaultAndroidVersion+ value.
Parsing of user supplied values::
    User defined properties on command line are automatically split by +,+ character and converted into array.

== Spacelift Tools and Task

You can benefit from following tools and tasks, either from Spacelift or provided by this plugin:

* DownloadTool - downloads a file
* UnzipTool - extracts a zip file
* CommandTool - executes external command
* AntExecutor - executes Ant command. Requires _ant_ tool
* MavenExecutor - executes Maven command. Requires _mvn_ tool
* JavaExecutor - executes Java command. Requires _java_ tool
* XmlFileLoader - loads xml from file into +Node+
* XmlTextLoader - loads xml from text into +Node+
* XmlUpdater - stores +Node+ into file
* ArquillianXmlUpdater - updates container and/or extension properties in _arquillian.xml_ files
* PomXmlUpdater - updates properties in _pom.xml_ files
* SettingsXmlUpdater - updates _settings.xml_ with additional repositories, sets +localRepository+
* KillJavas - kills running Java processes (Selenium, JBoss AS/WildFly containers) and processes occupying ports
* StandaloneXmlUpdater - allows to add keystore/truststore configuration to _standalone.xml_
* DomainXmlUpdater - allows to add keystore/truststore configuration to _domain.xml_
* AndroidSdkUpdater - allows to fetch binaries for specific Android SDK target - you need to agree with Android SDK license first. Requires _android_ tool.
* AndroidSdkOptForStats - allows to opt out for stats - you need to agree with Android SDK license first
*

